INSERT INTO brands (id, brand) VALUES
    (1, 'Seat'),
    (2, 'Renault'),
    (3, 'Peugeot'),
    (4, 'Dacia'),
    (5, 'Citroen'),
    (6, 'Opel'),
    (7, 'Alfa Romeo'),
    (8, 'Skoda'),
    (9, 'Chevrolet'),
    (10, 'Porsche'),
    (11, 'Honda'),
    (12, 'Subaru'),
    (13, 'Mazda'),
    (14, 'Mitsubishi'),
    (15, 'Lexus'),
    (16, 'Toyota'),
    (17, 'BMW'),
    (18, 'Volkswagen'),
    (19, 'Suzuki'),
    (20, 'Mercedes-Benz'),
    (21, 'Saab'),
    (22, 'Audi'),
    (23, 'Kia'),
    (24, 'Land Rover'),
    (25, 'Dodge'),
    (26, 'Chrysler'),
    (27, 'Ford'),
    (28, 'Hummer'),
    (29, 'Hyundai'),
    (30, 'Infiniti'),
    (31, 'Jaguar'),
    (32, 'Jeep'),
    (33, 'Nissan'),
    (34, 'Volvo'),
    (35, 'Daewoo'),
    (36, 'Fiat'),
    (37, 'MINI'),
    (38, 'Rover'),
    (39, 'Smart');
ALTER TABLE brands AUTO_INCREMENT = 40;